Repository Omicron-Team/Documentazione, pull requests merged in 2020-12, with the labels that each got.

#11 Fix template
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/DiarioModifiche.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/command.tex
  DocumentazioneEsterna/Glossario/res/DiarioModifiche.tex
  DocumentazioneEsterna/Glossario/res/command.tex
  DocumentazioneEsterna/PianiDiProgetto/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianiDiProgetto/res/command.tex
  DocumentazioneEsterna/PianiDiQualifica/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianiDiQualifica/res/command.tex
  DocumentazioneEsterna/VerbaliEsterni/VerbaleX/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VerbaleX/res/command.tex
  DocumentazioneInterna/NormeDiProgetto/res/DiarioModifiche.tex
  DocumentazioneInterna/NormeDiProgetto/res/command.tex
  DocumentazioneInterna/StudioDiFattibilita/res/DiarioModifiche.tex
  DocumentazioneInterna/StudioDiFattibilita/res/command.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/command.tex
  Utilita/latexSetup/styleTemplate.sty
Labels: BugGrafico, Miglioramento

#17 Miglioramento verbaleX
  DocumentazioneInterna/VerbaliInterni/VerbaleX/VerbaleX.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VerbaleX/res/command.tex
Labels: Miglioramento, Verbale

#21 Studio di fattibilita
  DocumentazioneEsterna/Glossario/Glossario.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/A.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/B.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/C.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/D.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/E.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/F.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/G.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/H.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/I.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/J.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/K.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/L.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/M.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/N.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/O.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/P.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Q.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/R.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/S.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/T.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/U.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/V.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/W.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/X.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Y.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Z.tex
  DocumentazioneEsterna/Glossario/res/DiarioModifiche.tex
  DocumentazioneEsterna/Glossario/res/command.tex
  DocumentazioneInterna/StudioDiFattibilita/StudioDiFattibilita.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C1/C1.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C2/C2.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C3/C3.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C4/C4.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C5/C5.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C6/C6.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C7/C7.tex
  DocumentazioneInterna/StudioDiFattibilita/res/C7/Resoconto.tex
  DocumentazioneInterna/StudioDiFattibilita/res/DiarioModifiche.tex
  DocumentazioneInterna/StudioDiFattibilita/res/Introduzione/Introduzione.tex
  DocumentazioneInterna/StudioDiFattibilita/res/command.tex
  Utilita/latexSetup/PrimaPagina.tex
  Utilita/latexSetup/generalCommand.tex
Labels: Approvazione, StudioFattibilità, Verifica
