Repository Omicron-Team/Documentazione, pull requests merged in 2021-01, with the labels that each got.

#81 Glossario
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/Glossario/Glossario.tex
  DocumentazioneEsterna/Glossario/buildGlossario.py
  DocumentazioneEsterna/Glossario/buildGlossarioForActions.py
  DocumentazioneEsterna/Glossario/glossario.csv
  DocumentazioneEsterna/Glossario/res/Alfabeto/A.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/B.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/C.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/D.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/E.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/F.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/G.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/H.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/I.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/J.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/K.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/L.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/M.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/N.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/O.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/P.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Q.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/R.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/S.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/T.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/U.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/V.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/W.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Z.tex
  DocumentazioneEsterna/Glossario/res/DiarioModifiche.tex
  DocumentazioneEsterna/Glossario/res/command.tex
Labels: Approvazione, Glossario, Verifica

#13 VI_2020-11-16 Verifica e Approvazione
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-16/VI_2020-11-16.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-16/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-16/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-16/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-16/res/command.tex
Labels: Approvazione, Verbale, Verifica

#14 VI_2020-12-02 Verifica e Approvazione
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/VI_2020-12-02.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/res/command.tex
Labels: Approvazione, Verbale, Verifica

#19 VI_2020-11-23 Verifica e Approvazione
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/VI_2020-11-23.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/res/command.tex
Labels: Approvazione, Verbale, Verifica

#20 VI_2020-12-09 Verifica e Approvazione
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/VI_2020-12-09.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-09/res/command.tex
Labels: Approvazione, Verbale, Verifica

#24 Ve 2020 12 11
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/VE_2020-12-11.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-11/res/command.tex
Labels: Approvazione, Verbale, Verifica

#32 VI_2020-12-23
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/VI_2020-12-23.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/VerbaleX.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-23/res/command.tex
Labels: Approvazione, Verbale, Verifica

#45 VE_2020-12-22
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/VE_2020-12-22.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2020-12-22/res/command.tex
Labels: Approvazione, Verbale, Verifica

#75 VE_2021-01-05
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/VE_2021-01-05.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-01-05/res/command.tex
Labels: Approvazione, Verbale, Verifica

#76 VI_2020-12-16
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/VI_2020-12-16.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2020-12-16/res/command.tex
Labels: Approvazione, Verbale, Verifica

#74 Piano di progetto
  DocumentazioneEsterna/PianoDiProgetto/PianoDiProgetto.tex
  DocumentazioneEsterna/PianoDiProgetto/res/AnalisiDeiRischi/analisiDeiRischi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Consuntivo/Fasi/analisi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Consuntivo/consuntivo.tex
  DocumentazioneEsterna/PianoDiProgetto/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/ModelloDiSviluppo/modelloDiSviluppo.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Francesco.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Gabriel.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Marco.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Matthew.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Niccolo.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Silvia.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/Firme/Tusa.png
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/organigramma.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/analisi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/codifica.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/progettazione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/verifica.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/analisi.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/codifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/incrementoCodifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/progettazione.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/verifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/pianificazione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Fasi/analisi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Fasi/codifica.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Fasi/progettazione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Fasi/verifica.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/areogramma_analisi.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/areogramma_codifica.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/areogramma_progettazione.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/areogramma_rendicontato.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/areogramma_totale.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/areogramma_verifica.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/istogramma_analisi.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/istogramma_codifica.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/istogramma_progettazione.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/istogramma_rendicontato.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/istogramma_totale.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/Img/istogramma_verifica.png
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/preventivo.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Preventivo/riepilogo.tex
  DocumentazioneEsterna/PianoDiProgetto/res/command.tex
Labels: Approvazione, PianoProgetto, Verifica

#80 Lettera presentazione RR
  .github/workflows/CompileFile.yml
  LetterePresentazioni/LetteraPresentazioneRR/Firma/Matthew.png
  LetterePresentazioni/LetteraPresentazioneRR/letteraRR.tex
  Utilita/latexSetup/styleLettera.sty
Labels: Presentazione

#77 Analisi dei requisiti
  DocumentazioneEsterna/AnalisiDeiRequisiti/AnalisiDeiRequisiti.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Descrizione/descrizione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/DiarioModifiche.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/funzionali.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/prestazionali.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/qualita.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/vincolo.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/requisiti.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Tracciamento/tracciamento.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Admin/useCaseAdmin.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Carrello/useCaseCarrello.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Checkout/useCaseCheckout.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Homepage/useCaseHomepage.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/AcquistoProdotti.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/AcquistoProdottiGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Admin.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/CarrelloGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/DiagrammaAttoriPrimari.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneCarrello.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneCategorie.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneProdotti.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneProfilo.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiAcquisto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiLoginCliente.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiLoginVenditore.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiPagamento.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiRegistrazione.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Login.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/LoginSottocasi.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Logout.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/MerchantDashboard.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/MerchantDashboardGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ModificaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ModificaProfilo.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/NavigazioneCatalogoGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ProfiloGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Registrazione.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/RegistrazioneGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazioneOrdini.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazioneOrdiniMerchant.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazionePaginaCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazionePaginaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Login/useCaseLogin.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Logout/useCaseLogout.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Merchant/useCaseMerchant.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/PDP/useCasePDP.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/PLP/useCasePLP.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Profilo/useCaseProfilo.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Registrazione/useCaseRegistrazione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/useCase.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/command.tex
Labels: AnalisiRequisiti, Approvazione, Verifica

#78 Piano di Qualifica
  DocumentazioneEsterna/PianoDiQualifica/PianoDiQualifica.tex
  DocumentazioneEsterna/PianoDiQualifica/indiceGulpease.py
  DocumentazioneEsterna/PianoDiQualifica/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianoDiQualifica/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/Introduzione/res/riferimenti.tex
  DocumentazioneEsterna/PianoDiQualifica/res/MiglioramentoDiProcesso/miglioramentoDiProcesso.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/qualitaDiProcesso.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/res/organizzativi.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/res/primari.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/res/supporto.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProdotto/qualitaDiProdotto.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/esitiIndiceGulpease.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/graficoGulpease.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/img/indiceGulpease.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/resocontoAttivitaDiVerifica.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoVerifica/resocontoVerifica.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/res/metricheDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/res/tabelleDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/specificheDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheTest/specificheTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/res/valutazioneOrganizzazione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/res/valutazioneRuoli.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/res/valutazioneStrumentiDiLavoro.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/valutazionePerIlMiglioramento.tex
  DocumentazioneEsterna/PianoDiQualifica/res/command.tex
  DocumentazioneEsterna/PianoDiQualifica/res/deming.tex
  Utilita/latexSetup/package.tex
Labels: Approvazione, PianoQualifica, Verifica
