Repository Omicron-Team/Documentazione, pull requests merged in 2021-04, with the labels that each got.

#119 VI_2021-03-10
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/VI_2021-03-10.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-10/res/command.tex
Labels: Approvazione, Verbale, Verifica

#116 Verbale Interno 21 03 17
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/VI_2021-03-17.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-17/res/command.tex
Labels: Approvazione, Verbale, Verifica

#122 VI_2021-03-20
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/VI_2021-03-20.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-03-20/res/command.tex
Labels: Approvazione, Verbale, Verifica

#125 VI_2021-04-12
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/VI_2021-04-12.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/Resoconto/res/Valutazione.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-12/res/command.tex
Labels: Approvazione, Verbale, Verifica

#121 Analisi dei requisiti
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/DiarioModifiche.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/funzionali.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/vincolo.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Tracciamento/tracciamento.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Carrello/useCaseCarrello.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Checkout/useCaseCheckout.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Homepage/useCaseHomepage.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/AcquistoProdotti.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/AcquistoProdottiGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/CarrelloGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneCarrello.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneCategorie.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneProdotti.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneProfilo.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiAcquisto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiPagamento.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaCategoriaGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaProdottoGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Login.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Logout.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/MerchantDashboard.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ModificaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ModificaProfilo.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/NavigazioneCatalogoGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ProfiloGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/RegistrazioneGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazioneOrdini.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazioneOrdiniMerchant.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Login/useCaseLogin.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Logout/useCaseLogout.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Merchant/useCaseMerchant.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/PDP/useCasePDP.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/PLP/useCasePLP.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Profilo/useCaseProfilo.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Registrazione/useCaseRegistrazione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/useCase.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/command.tex
Labels: AnalisiRequisiti, Approvazione, Verifica

#115 Verbale esterno 2021 03 31
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/VE_2021-03-31.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-31/res/command.tex
Labels: Approvazione, Verbale, Verifica

#117 stesura VE_2021-03-16
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/VE_2021-03-16.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-16/res/command.tex
Labels: Approvazione, Verbale, Verifica

#124 Glossario
  DocumentazioneEsterna/Glossario/glossario.csv
  DocumentazioneEsterna/Glossario/res/DiarioModifiche.tex
  DocumentazioneEsterna/Glossario/res/command.tex
Labels: Approvazione, Glossario, Verifica
