Repository Omicron-Team/Documentazione, pull requests merged in 2021-03, with the labels that each got.

#102 Piano di qualifica
  DocumentazioneEsterna/PianoDiQualifica/PianoDiQualifica.tex
  DocumentazioneEsterna/PianoDiQualifica/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianoDiQualifica/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/Introduzione/res/riferimenti.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/qualitaDiProcesso.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/res/organizzativi.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/res/primari.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/res/supporto.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProdotto/qualitaDiProdotto.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/analisi/analisi.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/analisi/revisioneDellaDocumentazione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/esitiIndiceGulpease.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/graficiProcessiOrganizzativi.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/graficiProcessiSupporto.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/actualCost.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/budgetVariance.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/correttezzaOrtografica.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/estimateCompletion.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeaseADR.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeaseG.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeaseNDP.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeasePDP.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeasePDQ.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeaseSDF.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/indiceGulpease.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/metricheSoddisfatte.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/varianceCompletion.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/metriche.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/progettazioneArchitetturale/progettazioneArchitetturale.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/progettazioneArchitetturale/revisioneDellaDocumentazione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/resocontoAttivitaDiVerifica.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/res/tabelleDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/specificheDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/res/valutazioneOrganizzazione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/res/valutazioneRuoli.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/res/valutazioneStrumentiDiLavoro.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ValutazionePerIlMiglioramento/valutazionePerIlMiglioramento.tex
  DocumentazioneEsterna/PianoDiQualifica/res/command.tex
Labels: Approvazione, PianoQualifica, Verifica

#93 VE_2021-02-17 Verifica e approvazione
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/VE_2021-02-17.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-17/res/command.tex
Labels: Approvazione, Verbale, Verifica

#97 VE_2021-02-04
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/VE_2021-02-04.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-02-04/res/command.tex
Labels: Approvazione, Verbale, Verifica

#107 VE_2021-03-01
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/VE_2021-03-01.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-03-01/res/command.tex
Labels: Approvazione, Verbale, Verifica

#103 Piano di Progetto
  DocumentazioneEsterna/PianoDiProgetto/PianoDiProgetto.tex
  DocumentazioneEsterna/PianoDiProgetto/res/AnalisiDeiRischi/analisiDeiRischi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/AnalisiDeiRischi/attuazioneRischi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Consuntivo/Fasi/analisi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Consuntivo/Fasi/progettazione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Consuntivo/consuntivo.tex
  DocumentazioneEsterna/PianoDiProgetto/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/ModelloDiSviluppo/modelloDiSviluppo.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Organigramma/organigramma.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/analisi.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/codifica.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/progettazione.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Fasi/verifica.tex
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/codifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/incCodifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/incProgettazione.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/incrementoCodifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/progettazione.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/Pianificazione/Gantt/verifica.PNG
  DocumentazioneEsterna/PianoDiProgetto/res/command.tex
Labels: Approvazione, PianoProgetto, Verifica

#108 Lettera presentazione RP
  .github/workflows/CompileFile.yml
  LetterePresentazioni/LetteraPresentazioneRP/Firma/Niccolo.png
  LetterePresentazioni/LetteraPresentazioneRP/letteraRP.tex
Labels: Presentazione

#106 Analisi dei requisiti
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/DiarioModifiche.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Introduzione/introduzione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/funzionali.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/qualita.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/TabelleRequisiti/vincolo.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Requisiti/requisiti.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/Tracciamento/tracciamento.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Admin/useCaseAdmin.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Carrello/useCaseCarrello.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Checkout/useCaseCheckout.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Homepage/useCaseHomepage.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/AcquistoProdotti.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/AcquistoProdottiGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Admin.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/CarrelloGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/DiagrammaAttoriPrimari.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneCarrello.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneCategorie.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneProdotti.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/GestioneProfilo.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiAcquisto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiLogin.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiLoginCliente.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiLoginVenditore.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoDatiPagamento.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InserimentoProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaCategoriaGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/InterazionePaginaProdottoGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/Login.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/LoginSottocasi.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/MerchantDashboard.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/MerchantDashboardGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ModificaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ModificaProfilo.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/NavigazioneCatalogoGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/ProfiloGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/RegistrazioneGenerale.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazioneOrdini.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazioneOrdiniMerchant.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazionePaginaCategoria.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Immagini/VisualizzazionePaginaProdotto.png
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Login/useCaseLogin.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Logout/useCaseLogout.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Merchant/useCaseMerchant.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/PDP/useCasePDP.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/PLP/useCasePLP.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Profilo/useCaseProfilo.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/Registrazione/useCaseRegistrazione.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/UseCase/useCase.tex
  DocumentazioneEsterna/AnalisiDeiRequisiti/res/command.tex
Labels: AnalisiRequisiti, Approvazione

#104 Glossario
  DocumentazioneEsterna/Glossario/glossario.csv
  DocumentazioneEsterna/Glossario/res/Alfabeto/A.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/B.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/C.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/D.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/E.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/F.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/G.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/H.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/I.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/J.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/K.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/L.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/M.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/N.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/O.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/P.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Q.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/R.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/S.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/T.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/U.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/V.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/W.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/X.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Y.tex
  DocumentazioneEsterna/Glossario/res/Alfabeto/Z.tex
  DocumentazioneEsterna/Glossario/res/DiarioModifiche.tex
  DocumentazioneEsterna/Glossario/res/command.tex
Labels: Approvazione, Glossario, Verifica

#99 VI_2021-02-22
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/VI_2021-02-22.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-22/res/command.tex
Labels: Approvazione, Verbale, Verifica

#96 VI 2021-02-16
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/VI_2021-02-16.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-16/res/command.tex
Labels: Approvazione, Verbale, Verifica

#95 VI_2021-02-09
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/VI_2021-02-09.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-02-09/res/command.tex
Labels: Approvazione, Verbale, Verifica
