Repository Omicron-Team/Documentazione, pull requests merged in 2021-05, with the labels that each got.

#133 VI 2021-05-09
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/VI_2021-05-09.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-05-09/res/command.tex
Labels: Approvazione, Verbale, Verifica

#136 Vi 2021 04 24
  .github/workflows/CompileFile.yml
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/VI_2021-04-24.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/res/DiarioModifiche.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/res/InformazioniGenerali.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/res/Resoconto/resoconto.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/res/Riepilogo.tex
  DocumentazioneInterna/VerbaliInterni/VI_2021-04-24/res/command.tex
Labels: Approvazione, Verbale, Verifica

#142 VE_2021-05-19
  .github/workflows/CompileFile.yml
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/VE_2021-05-19.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/res/DiarioModifiche.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/res/InfoGenerali.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/res/OrdineDelGiorno/ordineDelGiorno.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/res/Resoconto/resoconto.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/res/RiepilogoDecisioni.tex
  DocumentazioneEsterna/VerbaliEsterni/VE_2021-05-19/res/command.tex
Labels: Approvazione, Verbale, Verifica

#140 Norme di progetto
  DocumentazioneInterna/NormeDiProgetto/res/DiarioModifiche.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiOrganizzativi/Formazione/formazione.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiOrganizzativi/GestioneProcesso/Pianificazione/res/metricheQualita.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiPrimari/res/Fornitura.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiPrimari/res/res/codifica.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiPrimari/res/res/metricheAdR.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiPrimari/res/res/metricheCod.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiPrimari/res/res/tabFornitura.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiSupporto/res/documentazione.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiSupporto/res/gestioneQualita.tex
  DocumentazioneInterna/NormeDiProgetto/res/ProcessiSupporto/res/res/metricheVer.tex
  DocumentazioneInterna/NormeDiProgetto/res/command.tex
Labels: Approvazione, NormeProgetto, Verifica

#146 Glossario
  DocumentazioneEsterna/Glossario/res/DiarioModifiche.tex
  DocumentazioneEsterna/Glossario/res/command.tex
Labels: Approvazione, Glossario, Verifica

#145 Piano di qualifica
  DocumentazioneEsterna/PianoDiQualifica/PianoDiQualifica.tex
  DocumentazioneEsterna/PianoDiQualifica/res/DiarioModifiche.tex
  DocumentazioneEsterna/PianoDiQualifica/res/Introduzione/res/riferimenti.tex
  DocumentazioneEsterna/PianoDiQualifica/res/QualitaDiProcesso/qualitaDiProcesso.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/CCBE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/CCFE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/CompletezzaInformazioni.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/DensitaErrori.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/FCBE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/FCFE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/FacilitaApprendimento.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/FacilitaUtilizzo.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/MTS1.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/MTS2.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/PROS.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/PRS.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/SCBE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/SCFE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/SFBE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/SFFE.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/actualCost.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/budgetVariance.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/correttezzaOrtografica.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/dimensioneGerarchia.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/estimateCompletion.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeaseG.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeaseNDP.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeasePDP.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/gulpeasePDQ.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/indiceGulpease.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/metricheSoddisfatte.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/scheduleVariance.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/img/varianceCompletion.png
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/qualitàProcesso/graficiProcessiOrganizzativi.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/qualitàProcesso/graficiProcessiPrimari.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/qualitàProcesso/graficiProcessiSupporto.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/grafici/qualitàProdotto/qualitàProdotto.xlsx
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/metriche/metriche.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/validazioneECollaudo/revisioneDelCodice.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/validazioneECollaudo/revisioneDellaDocumentazione.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/res/validazioneECollaudo/validazioneECollaudo.tex
  DocumentazioneEsterna/PianoDiQualifica/res/ResocontoAttivitaDiVerifica/resocontoAttivitaDiVerifica.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/res/tabelleDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/SpecificheDeiTest/specificheDeiTest.tex
  DocumentazioneEsterna/PianoDiQualifica/res/command.tex
Labels: Approvazione, PianoQualifica, Verifica

#144 Developer manual
  DocumentazioneEsterna/DeveloperManual/DeveloperManual.tex
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Backend/img/diagrammaClassiBack-end.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Backend/img/handler_package.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Backend/img/layerBack-end.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Backend/img/package-back-end.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Backend/img/services_class.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/Components.tex
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/Services.tex
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/Types.tex
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/cart.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/class_frontend_types.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/dashboard.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/editProfile.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/modifyProduct.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/order.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/plp.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/profile.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/search.png
  DocumentazioneEsterna/DeveloperManual/res/Architettura/Frontend/img/services_frontend_class.png
  DocumentazioneEsterna/DeveloperManual/res/DiarioModifiche.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Configurazione/ConfigBackend.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Configurazione/ConfigEnv.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Configurazione/ConfigFrontend.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Configurazione/Configurazione.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Installazione/ModuloBackend.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Installazione/ModuloFrontend.tex
  DocumentazioneEsterna/DeveloperManual/res/Setup/Requisiti/Requisiti.tex
  DocumentazioneEsterna/DeveloperManual/res/Sviluppo/SviluppoBackend.tex
  DocumentazioneEsterna/DeveloperManual/res/Sviluppo/SviluppoFrontend.tex
  DocumentazioneEsterna/DeveloperManual/res/command.tex
Labels: Approvazione, DevManual, Verifica
